### PR TITLE
hvf-Products

### PR DESCRIPTION
**Pull request by hfrankst**

### CODE REVIEW

**Comment by ghost** [comment]
looking good so far!

**Comment by hfrankst** [comment]
I will keep working and pushing, but I would like to merge this request by the time we leave for the day.

**Comment by ghost** [comment]
only thing I noticed is that we still need descriptions... looking awesome!
also love how the images are specific to each type of recycling 👍

**Comment by hfrankst** [comment]
Alright. I've committed the descriptions.  If everyone is alright with it, I'll merge.  Probably going to be my last bit of work on this project tonight.  I want to get into some of the javascript exercises that I'm behind on :/

**Comment by ghost** [comment]
I see the descriptions in the commits, but I don't see the descriptions on the actual browser page.... I think maybe they still need pushed?

**Comment by hfrankst** [comment]
So whenever I tried to put full descriptions on the cards, they would resize and get way out of control.  I put a schedule on the cards in place of full descriptions.

**Pull request merged**
